version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PASSWORD: 'pass'
      DB_NAME: 'kevd'
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - .:/kevd
    links:
      - mysql
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_DATABASE: kevd
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    hostname: db
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local