web_push:
  :vapid_public_key: <%= ENV['VAPID_PUBLIC_KEY'] %>
  :vapid_private_key: <%= ENV['VAPID_PRIVATE_KEY'] %>
development:
  secret_key_base: kevd_app_development_mode

test:
  secret_key_base: kevd_app_test_mode

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
